CREATE TABLE schedule (
        schedule_id BIGINT AUTO_INCREMENT PRIMARY KEY,
        author VARCHAR(255) NOT NULL ,
        content VARCHAR(255) NOT NULL,
        create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        password VARCHAR(255) NOT NULL
);